(in-package #:termdown/tests)

(defun test-span-presentation ()
  "Test safe rendering, role preservation, grapheme clipping and cell limits."
  (let* ((accent (string (code-char #x301)))
         (spans (list (make-span ':plain "e") (make-span ':strong accent)
                      (make-span ':code "界z"))))
    (loop for width from -1 to 5
          for expected in (list "" "" (concatenate 'string "e" accent)
                                (concatenate 'string "e" accent)
                                (concatenate 'string "e" accent "界")
                                (concatenate 'string "e" accent "界z")
                                (concatenate 'string "e" accent "界z"))
          for fitted = (termdown:fit-spans spans width)
          do (test-assert (string= (termdown:spans-text fitted) expected)
                          "fitting retains complete cross-span graphemes")
             (test-assert (<= (text-cell-width (termdown:spans-text fitted))
                              (max 0 width))
                          "fitting obeys the cell budget")))
  (let* ((unsafe (format nil "a~C[31mb~%c" #\Escape))
         (spans (list (make-span ':strong unsafe)))
         (seen nil)
         (rendered
           (termdown:render-spans
            spans :style-function
            (lambda (role text)
              (push (cons role text) seen)
              (concatenate 'string "[" text "]")))))
    (test-assert (equal seen (list (cons ':strong (clinedi:sanitize-text unsafe))))
                 "style callbacks receive semantic roles and sanitized text")
    (test-assert (string= rendered
                          (concatenate 'string "[" (clinedi:sanitize-text unsafe) "]"))
                 "trusted presentation surrounds only safe text")
    (test-assert (string= (termdown:render-spans spans)
                          (termdown:spans-text spans))
                 "unstyled rendering returns sanitized text")
    (test-assert (not (find #\Newline (termdown:spans-text spans :single-line-p t)))
                 "single-line presentation removes row breaks"))
  t)

(defun test-widget-regions ()
  "Test that widgets present as spans and their regions locate their actions."
  (let* ((copy (termdown:make-widget ':code-copy "copy" '(:copy "source")))
         (items (list (termdown:make-span ':plain (format nil "a~Cb " #\Tab))
                      copy
                      (termdown:make-widget ':dim "" '(:never))
                      (termdown:make-span ':plain " z")))
         (text (termdown:spans-text items))
         (regions (termdown:widget-regions items)))
    (test-assert (string= text "a    b copy z")
                 "widgets present as their labels among sanitized spans")
    (test-assert (equal regions '((7 11 (:copy "source"))))
                 "regions count sanitized characters and skip empty labels")
    (test-assert (string= (subseq text 7 11) "copy")
                 "a region covers exactly its label")
    (test-assert (and (null (termdown:region-action regions 6))
                      (equal (termdown:region-action regions 7) '(:copy "source"))
                      (equal (termdown:region-action regions 10) '(:copy "source"))
                      (null (termdown:region-action regions 11)))
                 "region actions cover half-open character ranges")
    (test-assert (equal (termdown:widget-regions items :start 5)
                        (termdown:shift-regions regions 5))
                 "a start offset equals shifting the regions")
    (test-assert (eq (termdown:shift-regions regions 0) regions)
                 "a zero shift returns the regions unchanged")
    (test-assert (equal (termdown:render-spans
                         items
                         :style-function (lambda (role text)
                                           (if (eq role ':code-copy)
                                               (concatenate 'string "[" text "]")
                                               text)))
                        "a    b [copy] z")
                 "widgets render through the style of their role")
    (test-assert (= (termdown:spans-width (list copy)) 4)
                 "widgets count toward the row width")
    (test-assert (equal (termdown:fit-spans items 9)
                        (list (termdown:make-span ':plain "a    b ")
                              (termdown:make-span ':code-copy "co")))
                 "fitting presents widgets as clipped spans")
    (test-assert (eq (termdown:widget-role copy) ':code-copy)
                 "widgets keep their role"))
  t)
